### ISSUE TITLE
it not work

### ISSUE THREAD

**Issue by Alexloi4071** [tahaluindo/Tiktok-ViewsBOT#6]
Traceback (most recent call last):
  File "c:\Users\XXX\Tiktok-ViewsBOT-main\v3.py", line 250, in <module>
    Main().main()
  File "c:\Users\XXX\Tiktok-ViewsBOT-main\v3.py", line 235, in main
    sessid: str = self.get_sessid()
  File "c:\XXX\Tiktok-ViewsBOT-main\v3.py", line 139, in get_sessid
    sessid = self.session.get(
IndexError: list index out of range

**Comment by tahaluindo** [comment]
python barubang.py
